### ISSUE TITLE
What does each element in the matrix represent?

### ISSUE THREAD

**Issue by twitchyliquid64** [HW21/sparse21#1]
Hi! Apologies if this is a silly question, a lot of this is new and I'm still learning.

For funzies, I'm trying to make something that can solve the linear system you get when you write out the equations of voltage sources and resistors. I have these as an augmented matrix of the coefficients and the right hand side ([like on Wikipedia](https://en.wikipedia.org/wiki/Augmented_matrix#Existence_and_number_of_solutions)).

Is that what I need to plumb into `sparse21::Matrix::add_element()` or is each row/column symbolic of some other representation of a linear system?

**Comment by dan-fritchman** [comment]
Great funzies project! 

Some hopefully helpful links: 
* https://medium.com/software-makes-hardware/analog-transistor-level-simulation-f15d2a233508
* https://github.com/HW21/TeachSpice

Or if you really wanna go full funzie, dig into Spice21: 
* https://github.com/dan-fritchman/spice21

**Comment by twitchyliquid64** [comment]
Thanks!

> https://medium.com/software-makes-hardware/analog-transistor-level-simulation-f15d2a233508

This is behind a hard-paywall, do you happen to have a copy elsewhere?

**Comment by dan-fritchman** [comment]
https://dan.fritch.mn/SwMakesHw/0004-analog-simulation

**Comment by twitchyliquid64** [comment]
Thank you!

I think this is one of those things where I need to stare at it a while. The concept of building up a linear equation to describe a bunch of passives in a circuit makes sense, but actually writing the code to translate a netlist into a series of equations is another thing.

As for my original question, I think Ive worked it out: each element `(x, y)` in the input `sparse21::Matrix` matrix represents a coefficient, where `x` is the zero-index of the variable the coefficient is for, and `y` is the zero-index of which linear equation you are providing the coefficients for (i.e. the number of `y`'s should match the number of elements in the vector passed to `.solve()`).

Is this correct?

I think so, because the following test passes:

```rust
    #[test]
    fn sparse21_takes_coefficient_matrix() {
        // 8x - 15 = 17:
        //  var[0] = x
        //  var[1] = constant 1
        let mut m = sparse21::Matrix::from_entries(vec![
            (0, 0, 8.0),    // '8x' of equation
            (0, 1, -15.0),  // '-15' of equation
            (1, 1, 1.0),    // hack for constant
        ]);

        let soln = m.solve(vec![17.0, 1.0]).unwrap();

        assert_eq!(soln, vec![4.0, 1.0]);
    }
```

Took me longer than I'm willing to admit to realize you can just express constants as a variable with a value of 1 :sweat_smile:
